"""Canonical parameter contract — single source of truth for all 24 input parameters.

Each entry documents: name, Python type, unit, default value, min/max bounds,
enum values (if applicable), and which calculation formulas the parameter affects.
"""

from .enums import Material, BlankType, ElectricityGrid, ALL_RECYCLED_CONTENT

PARAMETER_CONTRACT = [
    {
        "name": "material",
        "type": "enum",
        "unit": None,
        "default": "Alloy-F",
        "min": None,
        "max": None,
        "enum_values": [m.value for m in Material],
        "formulas_affected": ["raw_material", "upstream_processing"],
        "description": "Aluminum alloy or plastic material type. Also determines specific heat for heat_treatment (aluminum vs plastic).",
    },
    {
        "name": "recycled_content",
        "type": "int",
        "unit": "%",
        "default": 0,
        "min": 0,
        "max": 100,
        "enum_values": ALL_RECYCLED_CONTENT,
        "formulas_affected": ["raw_material"],
        "description": "Percentage of recycled content in raw material (0, 25, 30, 50, 75, 100)",
    },
    {
        "name": "raw_material_blank_type",
        "type": "enum",
        "unit": None,
        "default": "Extruded",
        "min": None,
        "max": None,
        "enum_values": [b.value for b in BlankType],
        "formulas_affected": ["upstream_processing", "die_casting"],
        "description": "Upstream blank form: determines semi-fabrication pathway",
    },
    {
        "name": "final_part_mass",
        "type": "float",
        "unit": "g",
        "default": None,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": [],
        "description": "Weight of finished part (informational, not used in current formulas)",
    },
    {
        "name": "final_part_volume",
        "type": "float",
        "unit": "mm3",
        "default": None,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": [],
        "description": "Volume of finished part (informational)",
    },
    {
        "name": "raw_material_mass",
        "type": "float",
        "unit": "g",
        "default": 1000.0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": [
            "raw_material", "upstream_processing", "stamping",
            "heat_treatment", "die_casting",
        ],
        "description": "Weight of raw material blank (required)",
    },
    {
        "name": "raw_material_volume",
        "type": "float",
        "unit": "mm3",
        "default": None,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": [],
        "description": "Volume of raw material blank (informational)",
    },
    {
        "name": "final_part_yield",
        "type": "float",
        "unit": "fraction",
        "default": 0.90,
        "min": 0,
        "max": 1,
        "enum_values": None,
        "formulas_affected": [],
        "description": "Manufacturing yield fraction (informational in current model)",
    },
    {
        "name": "plastic_injection_molding_parts_per_shot",
        "type": "int",
        "unit": "count",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["injection_molding"],
        "description": "Number of parts per injection molding shot (0 = not used)",
    },
    {
        "name": "plastic_injection_molding_cycle_time",
        "type": "float",
        "unit": "sec/shot",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["injection_molding"],
        "description": "Injection molding cycle time per shot",
    },
    {
        "name": "forging_strikes",
        "type": "int",
        "unit": "count",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["forging"],
        "description": "Number of forging strikes (500-ton press, 0.01 kWh/strike)",
    },
    {
        "name": "forging_trimming_bending_strikes",
        "type": "int",
        "unit": "count",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["forging"],
        "description": "Number of trimming/bending strikes (110-ton press, 0.005 kWh/strike)",
    },
    {
        "name": "stamping_steps",
        "type": "int",
        "unit": "count",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["stamping"],
        "description": "Number of stamping press operations",
    },
    {
        "name": "heat_treatment_annealing_steps",
        "type": "int",
        "unit": "count",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["heat_treatment"],
        "description": "Number of annealing heat treatment steps",
    },
    {
        "name": "heat_treatment_annealing_temperature",
        "type": "float",
        "unit": "C",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["heat_treatment"],
        "description": "Annealing target temperature in Celsius",
    },
    {
        "name": "heat_treatment_tempering_steps",
        "type": "int",
        "unit": "count",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["heat_treatment"],
        "description": "Number of tempering heat treatment steps",
    },
    {
        "name": "heat_treatment_tempering_temperature",
        "type": "float",
        "unit": "C",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["heat_treatment"],
        "description": "Tempering target temperature in Celsius",
    },
    {
        "name": "laser_cutting_welding_cycle_time",
        "type": "float",
        "unit": "sec/pc",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["laser"],
        "description": "Laser cutting or welding cycle time (4.0 kW power)",
    },
    {
        "name": "laser_etching_cycle_time",
        "type": "float",
        "unit": "sec/pc",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["laser"],
        "description": "Laser etching cycle time (0.145 kW power)",
    },
    {
        "name": "sanding_cycle_time",
        "type": "float",
        "unit": "sec/pc",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["sanding"],
        "description": "Sanding cycle time (0.6 kW power)",
    },
    {
        "name": "machining_cycle_time",
        "type": "float",
        "unit": "sec/pc",
        "default": 0,
        "min": 0,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["machining"],
        "description": "CNC machining cycle time (2.0 kW avg power)",
    },
    {
        "name": "anodizing",
        "type": "bool",
        "unit": None,
        "default": False,
        "min": None,
        "max": None,
        "enum_values": None,
        "formulas_affected": ["anodizing"],
        "description": "Whether anodizing is applied (0.2 kWh/step)",
    },
    {
        "name": "electricity_grid",
        "type": "enum",
        "unit": "kg CO2e/kWh",
        "default": "Region A",
        "min": None,
        "max": None,
        "enum_values": [g.value for g in ElectricityGrid],
        "formulas_affected": [
            "upstream_processing", "forging", "stamping", "heat_treatment",
            "machining", "laser", "sanding", "die_casting",
            "injection_molding", "anodizing",
        ],
        "description": "Manufacturing electricity grid (affects all grid-dependent processes)",
    },
]

# Quick lookup by parameter name
PARAMETER_MAP = {p["name"]: p for p in PARAMETER_CONTRACT}
