import type { ScenarioInput, ProcessBreakdown, ProductContext, FieldProvenance, ModelValidity } from "../../types";
import { PROCESS_LABELS } from "../../types";
import "./Report.css";

interface Props {
  input: ScenarioInput;
  breakdown: ProcessBreakdown | null;
  productContext: ProductContext;
  provenance: Record<string, FieldProvenance> | null;
  mappingWarnings: string[];
  productLabel: string;
  modelValidity: ModelValidity | null;
}

const PARAM_LABELS: Record<string, string> = {
  material: "Material",
  recycled_content: "Recycled Content",
  raw_material_blank_type: "Blank Type",
  raw_material_mass: "Raw Material Mass",
  final_part_yield: "Final Part Yield",
  electricity_grid: "Electricity Grid",
  forging_strikes: "Forging Strikes",
  forging_trimming_bending_strikes: "Trimming/Bending Strikes",
  stamping_steps: "Stamping Steps",
  machining_cycle_time: "Machining Cycle Time",
  laser_cutting_welding_cycle_time: "Laser Cut/Weld Time",
  laser_etching_cycle_time: "Laser Etch Time",
  sanding_cycle_time: "Sanding Time",
  anodizing: "Anodizing",
  plastic_injection_molding_parts_per_shot: "IM Parts/Shot",
  plastic_injection_molding_cycle_time: "IM Cycle Time",
  heat_treatment_annealing_steps: "Annealing Steps",
  heat_treatment_annealing_temperature: "Annealing Temp",
  heat_treatment_tempering_steps: "Tempering Steps",
  heat_treatment_tempering_temperature: "Tempering Temp",
};

const PROCESS_KEYS = [
  "raw_material", "upstream_processing", "forging", "stamping",
  "heat_treatment", "machining", "laser", "sanding",
  "die_casting", "injection_molding", "anodizing",
] as const;

function ConfDot({ confidence }: { confidence: string }) {
  const colors: Record<string, string> = { high: "#27ae60", medium: "#f39c12", low: "#95a5a6" };
  return <span className="report-conf-dot" style={{ background: colors[confidence] || "#95a5a6" }} />;
}

export default function ScenarioReport({
  input, breakdown, productContext, provenance, mappingWarnings, productLabel, modelValidity,
}: Props) {
  if (!breakdown) {
    return (
      <div className="report-empty">
        <p>Select a product and component, or configure a scenario to generate a report.</p>
      </div>
    );
  }

  const inputDict = input as unknown as Record<string, unknown>;
  const now = new Date().toISOString().split("T")[0];

  return (
    <div className="report">
      <div className="report-header">
        <h2>Scenario Report</h2>
        <div className="report-meta">
          <span>Generated by Carbon Scenario Explorer</span>
          <span>{productLabel || "Custom Scenario"}</span>
          <span>{now}</span>
        </div>
        <button className="report-print-btn" onClick={() => window.print()}>
          Print / Export PDF
        </button>
      </div>

      {productContext.product_family && (
        <div className="report-section">
          <h3>Product Context</h3>
          <table className="report-table">
            <tbody>
              {productContext.product_family && <tr><td>Product Family</td><td>{productContext.product_family}</td></tr>}
              {productContext.component_type && <tr><td>Component</td><td>{productContext.component_type}</td></tr>}
              {productContext.part_name && <tr><td>Part Name</td><td>{productContext.part_name}</td></tr>}
              {productContext.preset_id && <tr><td>Baseline Preset</td><td>{productContext.preset_id}</td></tr>}
            </tbody>
          </table>
        </div>
      )}

      {modelValidity && (
        <div className={`report-section report-validity report-validity-${modelValidity.status}`}>
          <h3>Model Validity</h3>
          <div className="rv-status">
            <span className={`validity-badge validity-badge-${modelValidity.status}`}>
              {modelValidity.status === "validated" ? "Validated" : modelValidity.status === "approximate" ? "Approximate" : "Unsupported"}
            </span>
            <span>{modelValidity.message}</span>
          </div>
          {modelValidity.status !== "validated" && (
            <p className="rv-note">Results are based on a generic mass-based model and do not reflect category-specific methodology.</p>
          )}
        </div>
      )}

      {provenance && (
        <div className="report-section">
          <h3>Data Provenance Summary</h3>
          <table className="report-table">
            <thead>
              <tr><th>Field</th><th>Value</th><th>Source</th><th>Confidence</th></tr>
            </thead>
            <tbody>
              {["raw_material_mass", "material", "recycled_content", "raw_material_blank_type", "electricity_grid"].map((field) => {
                const p = provenance[field];
                if (!p) return null;
                return (
                  <tr key={field}>
                    <td>{PARAM_LABELS[field] || field}</td>
                    <td>{String(p.value)}{field === "recycled_content" ? "%" : ""}{field === "raw_material_mass" ? " g" : ""}</td>
                    <td>{p.source.replace(/_/g, " ")}</td>
                    <td><ConfDot confidence={p.confidence} /> {p.confidence}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {mappingWarnings.length > 0 && (
        <div className="report-section report-warnings">
          <h3>Mapping Warnings</h3>
          <ul>
            {mappingWarnings.map((w, i) => <li key={i}>{w}</li>)}
          </ul>
        </div>
      )}

      <div className="report-section">
        <h3>Scenario Parameters</h3>
        <table className="report-table">
          <thead>
            <tr><th>Parameter</th><th>Value</th></tr>
          </thead>
          <tbody>
            {Object.entries(PARAM_LABELS).map(([key, label]) => {
              const val = inputDict[key];
              if (val === 0 || val === null || val === undefined || val === false) return null;
              let display = String(val);
              if (key === "recycled_content") display += "%";
              if (key.includes("mass")) display += " g";
              if (key.includes("cycle_time") || key.includes("temperature")) {
                display += key.includes("temperature") ? " C" : " sec";
              }
              if (key === "anodizing") display = val ? "Yes" : "No";
              return <tr key={key}><td>{label}</td><td>{display}</td></tr>;
            })}
          </tbody>
        </table>
      </div>

      <div className="report-section">
        <h3>Carbon Footprint Breakdown</h3>
        <div className="report-total">
          <span className="report-total-label">Total</span>
          <span className="report-total-value">{breakdown.total.toFixed(4)} kg CO2e/unit</span>
        </div>
        <table className="report-table">
          <thead>
            <tr><th>Process</th><th>kg CO2e/unit</th><th>Share</th></tr>
          </thead>
          <tbody>
            {PROCESS_KEYS.filter((k) => (breakdown as Record<string, number>)[k] > 0.00001).map((key) => {
              const val = (breakdown as Record<string, number>)[key];
              const pct = breakdown.total > 0 ? (val / breakdown.total * 100) : 0;
              return (
                <tr key={key}>
                  <td>{PROCESS_LABELS[key]}</td>
                  <td>{val.toFixed(6)}</td>
                  <td>{pct.toFixed(1)}%</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <div className="report-footer">
        <p>Model version: {breakdown.model_version || "1.0.0"} | Data version: {breakdown.data_version || "2026-04-17"}</p>
        <p>This application is a public-safe demonstration of a configurable scenario analysis engine. Dataset content is illustrative. Values marked as "estimated" use component-level deltas applied to product baselines.</p>
      </div>
    </div>
  );
}
